defmodule PWeb.Endpoint do
  use Sentry.PlugCapture

  use Phoenix.Endpoint, otp_app: :photowalk
  import PhoenixVite.Plug

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_photowalk_key",
    signing_salt: "eDU+UpQf",
    same_site: "Lax",
    secure: true
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  plug :favicon, dev_server: {PhoenixVite.Components, :has_vite_watcher?, [__MODULE__]}

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :photowalk,
    gzip: not code_reloading?,
    only: PWeb.static_paths()

  plug Plug.Static,
    at: "/uploads",
    from:
      Application.compile_env(:waffle, :storage_dir_prefix)
      |> Path.join(Application.compile_env(:waffle, :storage_dir)),
    gzip: false,
    cache_control_for_etags: "public, max-age=31536000"

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :photowalk
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: Application.compile_env(:photowalk, :upload_max_bytes, 75_000_000)

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PWeb.Router

  plug Sentry.PlugContext
end
