/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/request-magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a magic link
         * @description Sends a magic link to the provided email address for passwordless authentication
         */
        post: operations["ThexstackWeb.AuthController.request_magic_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List todos for current user
         * @description Returns all todos belonging to the authenticated user
         */
        get: operations["ThexstackWeb.TodoController.index"];
        put?: never;
        /**
         * Create a new todo
         * @description Creates a new todo for the authenticated user
         */
        post: operations["ThexstackWeb.TodoController.create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a todo
         * @description Deletes an existing todo belonging to the authenticated user
         */
        delete: operations["ThexstackWeb.TodoController.delete"];
        options?: never;
        head?: never;
        /**
         * Update a todo
         * @description Updates an existing todo belonging to the authenticated user
         */
        patch: operations["ThexstackWeb.TodoController.update"];
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the currently authenticated user's information
         */
        get: operations["ThexstackWeb.UserController.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Todo
         * @description A todo item
         * @example {
         *       "completed": false,
         *       "id": 1,
         *       "inserted_at": "2024-01-01T12:00:00.000000Z",
         *       "title": "Buy milk",
         *       "updated_at": "2024-01-01T12:00:00.000000Z"
         *     }
         */
        Todo: {
            completed: boolean;
            id: number;
            /** Format: date-time */
            inserted_at: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * TodoListResponse
         * @description Response schema for listing Todo resources
         * @example {
         *       "data": [
         *         {
         *           "completed": false,
         *           "id": 1,
         *           "inserted_at": "2024-01-01T12:00:00.000000Z",
         *           "title": "Buy milk",
         *           "updated_at": "2024-01-01T12:00:00.000000Z"
         *         }
         *       ]
         *     }
         */
        TodoListResponse: {
            data: {
                completed: boolean;
                id: number;
                /** Format: date-time */
                inserted_at: string;
                title: string;
                /** Format: date-time */
                updated_at: string;
            }[];
        };
        TodosResponse: components["schemas"]["TodoListResponse"];
        /**
         * User
         * @description A user account
         * @example {
         *       "avatar_url": "https://gravatar.com/avatar/b58996c504c5638798eb6b511e6f49af",
         *       "confirmed_at": "2024-01-01T12:00:00.000000Z",
         *       "email": "user@example.com",
         *       "id": 1
         *     }
         */
        User: {
            /**
             * Format: uri
             * @description Gravatar URL based on user email
             */
            avatar_url?: string;
            /** Format: date-time */
            confirmed_at?: string;
            email: string;
            id: number;
        };
        /**
         * UserListResponse
         * @description Response schema for listing User resources
         * @example {
         *       "data": [
         *         {
         *           "avatar_url": "https://gravatar.com/avatar/b58996c504c5638798eb6b511e6f49af",
         *           "confirmed_at": "2024-01-01T12:00:00.000000Z",
         *           "email": "user@example.com",
         *           "id": 1
         *         }
         *       ]
         *     }
         */
        UserListResponse: {
            data: {
                /**
                 * Format: uri
                 * @description Gravatar URL based on user email
                 */
                avatar_url?: string;
                /** Format: date-time */
                confirmed_at?: string;
                email: string;
                id: number;
            }[];
        };
        UsersResponse: components["schemas"]["UserListResponse"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "ThexstackWeb.AuthController.request_magic_link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Email */
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description User's email address
                     */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Magic link sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        success?: boolean;
                    };
                };
            };
            /** @description Email is required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
            /** @description Email not authorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    "ThexstackWeb.TodoController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todos response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoListResponse"];
                };
            };
        };
    };
    "ThexstackWeb.TodoController.create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Todo attributes */
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description Completion status
                     * @default false
                     */
                    completed?: boolean;
                    /** @description Title of the todo */
                    title: string;
                };
            };
        };
        responses: {
            /** @description Todo created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description Validation errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    "ThexstackWeb.TodoController.delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todo ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Todo not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    "ThexstackWeb.TodoController.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todo ID */
                id: number;
            };
            cookie?: never;
        };
        /** @description Todo attributes */
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Completion status */
                    completed?: boolean;
                    /** @description Title of the todo */
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Todo updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            /** @description Todo not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    "ThexstackWeb.UserController.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** Format: date-time */
                            confirmed_at?: string | null;
                            /** Format: email */
                            email?: string;
                            id?: number;
                        };
                    };
                };
            };
        };
    };
}
