/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPhotosBackupRouteImport } from './routes/_app/photos-backup'
import { Route as AppWalksNewRouteImport } from './routes/_app/walks/new'
import { Route as AppWalksCollectionIdRouteImport } from './routes/_app/walks/$collectionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosBackupRoute = AppPhotosBackupRouteImport.update({
  id: '/photos-backup',
  path: '/photos-backup',
  getParentRoute: () => AppRoute,
} as any)
const AppWalksNewRoute = AppWalksNewRouteImport.update({
  id: '/walks/new',
  path: '/walks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWalksCollectionIdRoute = AppWalksCollectionIdRouteImport.update({
  id: '/walks/$collectionId',
  path: '/walks/$collectionId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signup': typeof SignupRoute
  '/photos-backup': typeof AppPhotosBackupRoute
  '/': typeof AppIndexRoute
  '/walks/$collectionId': typeof AppWalksCollectionIdRoute
  '/walks/new': typeof AppWalksNewRoute
}
export interface FileRoutesByTo {
  '/signup': typeof SignupRoute
  '/photos-backup': typeof AppPhotosBackupRoute
  '/': typeof AppIndexRoute
  '/walks/$collectionId': typeof AppWalksCollectionIdRoute
  '/walks/new': typeof AppWalksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/photos-backup': typeof AppPhotosBackupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/walks/$collectionId': typeof AppWalksCollectionIdRoute
  '/_app/walks/new': typeof AppWalksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signup'
    | '/photos-backup'
    | '/'
    | '/walks/$collectionId'
    | '/walks/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/signup' | '/photos-backup' | '/' | '/walks/$collectionId' | '/walks/new'
  id:
    | '__root__'
    | '/_app'
    | '/signup'
    | '/_app/photos-backup'
    | '/_app/'
    | '/_app/walks/$collectionId'
    | '/_app/walks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos-backup': {
      id: '/_app/photos-backup'
      path: '/photos-backup'
      fullPath: '/photos-backup'
      preLoaderRoute: typeof AppPhotosBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/walks/new': {
      id: '/_app/walks/new'
      path: '/walks/new'
      fullPath: '/walks/new'
      preLoaderRoute: typeof AppWalksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/walks/$collectionId': {
      id: '/_app/walks/$collectionId'
      path: '/walks/$collectionId'
      fullPath: '/walks/$collectionId'
      preLoaderRoute: typeof AppWalksCollectionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPhotosBackupRoute: typeof AppPhotosBackupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWalksCollectionIdRoute: typeof AppWalksCollectionIdRoute
  AppWalksNewRoute: typeof AppWalksNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPhotosBackupRoute: AppPhotosBackupRoute,
  AppIndexRoute: AppIndexRoute,
  AppWalksCollectionIdRoute: AppWalksCollectionIdRoute,
  AppWalksNewRoute: AppWalksNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
